### ISSUE TITLE
Failing on replicating the "index creation" example

### ISSUE THREAD

**Issue by Jean-Zombie** [RolandDreger/indesign-openai#1]
I am trying to replicate the impressive index creation from your Vimeo examples but w/o success. 

Passing the text to the plugin and communication with the OpenAi servers works flawless. I just can’t see how the actual index get’s created. If I insert the result of my create-index-keywords-prompt, well, the selected text get’s replaced with those words – kind as expected :-). Is there another script involved or does the plugin need the index panel to be involved somehow?

**Comment by RolandDreger** [comment]
I'm currently experimenting if and how OpenAI can be used in a useful way in InDesign. This was a temporary experiment with an (very simplified) additional function. I think things will get interesting when AI can interact directly with InDesign. But it's not that far yet.

In the meantime you could process the result with Marc Autret's (@indiscripts) script [IndexMatic³](https://indiscripts.com/post/2023/05/indexmatic3-in-the-spotlight-creative-pro-magazine). Or ask Marc, maybe he also plans to integrate such a function into his script.

**Comment by Jean-Zombie** [comment]
I see, thanks for taking the time to reply and clarify.
