### ISSUE TITLE
Indesign version?

### ISSUE THREAD

**Issue by dscholtus** [RolandDreger/indesign-openai#3]
<img width="1392" alt="Screenshot 2023-12-04 at 12 27 57" src="https://github.com/RolandDreger/indesign-openai/assets/16437945/14e00d1d-ec80-434a-9099-1927b8dba4c3">

Hi Roland, great idea to implement openai in indesign, I have the newest but I get this error. Is there a way to update your repo (can I do it myself?)

**Comment by RolandDreger** [comment]
Hi,

I just tried it on my system and reinstalled the plugin. MacOS + InDesign 2023, 2024. Hard to say what the reason is in your case 

Are you installing the plugin by double-clicking on the file #openai-4-indesign.ccx?

Roland
