### ISSUE TITLE
Free version supported?

### ISSUE THREAD

**Issue by l0oo** [RolandDreger/indesign-openai#4]
Hello!
Will indesign-openai script/plugin work with free version of GPT-3.5, or Plus only? Seems like very nice tool! :) 
BTW I'd like to ask CatGPT to help me with ID *.jsx writing [possible with automatic load of written script, and debug if needed etc etc ...]) ;)
Rgrds

**Comment by RolandDreger** [comment]
> Will indesign-openai script/plugin work with free version of GPT-3.5, or Plus only? Seems like very nice tool! :)

Unfortunately no, you must specify a payment option at OpenAI. However, [the amounts charged per promt via API are very low.](https://help.openai.com/en/articles/7127956-how-much-does-gpt-4-cost)

However, here is another approach from colleagues. I think you don't need to register with OpenIA here: [Project Octopus](https://www.project-octopus.net/script-help/)

> BTW I'd like to ask CatGPT to help me with ID *.jsx writing [possible with automatic load of written script, and debug if needed etc etc ...]) ;)

I know that there is an experimental plugin for Photoshop that does this. I have also tried it for InDesign. But the scripts created by the AI should still be treated with caution. For example, during a test, one wanted to delete pages in the document when asked to simply change a setting. Not what you necessarily want. ;)

**Comment by l0oo** [comment]
> However, here is another approach from colleagues. I think you don't need to register with OpenIA here: [Project Octopus](https://www.project-octopus.net/script-help/)

Thanks for the link! I will try Octopus Help for sure. :)

> > BTW I'd like to ask CatGPT to help me with ID *.jsx writing [possible with automatic load of written script, and debug if needed etc etc ...]) ;)
> 
> I know that there is an experimental plugin for Photoshop that does this. I have also tried it for InDesign. But the scripts created by the AI should still be treated with caution. For example, during a test, one wanted to delete pages in the document when asked to simply change a setting. Not what you necessarily want. ;)

Sure! I've made small script (with help of ChatGPT, as non programmer) for my specific needs and it wasn't easy nor quick. But it works. (Of course all experiments was made in test file, not the important one.) Anyway - trial and error approach was true time eater. :)
