### ISSUE TITLE
custom openai model such as gpt4 turbo / and or Claude // custom

### ISSUE THREAD

**Issue by dscholtus** [RolandDreger/indesign-openai#6]
Hi Roland,

Big fan use the indesign + gpt  all day every day.
How can I edit the file to add my custom GPT?

**Comment by RolandDreger** [comment]
Hi!
I can integrate GPT-4 turbo, it's not a big deal. Integrating a custom GPT or Claude would mean a bit more work. I can do that for you individually. If you are interested, please get in touch.

Roland

**Comment by RolandDreger** [comment]
New OpenAI models added in release [v1.4.2](https://github.com/RolandDreger/indesign-openai/releases/tag/v1.4.2)
